In [1]:
import pandas as pd

In [6]:
# First 30 activations for layerX at 3 different iteration steps
df = pd.read_parquet('layer2 0 conv2.parquet')
df.head(30)

    iter_128  iter_512  iter_1024
0  -0.001465 -0.011621  -0.012079
1  -0.002628 -0.004541  -0.005254
2  -0.014055 -0.014814  -0.021501
3  -0.006005 -0.013163  -0.011499
4  -0.002743 -0.003536  -0.003469
5  -0.007362 -0.021878  -0.011562
6  -0.044467 -0.017011   0.005724
7  -0.012194 -0.018946  -0.021520
8  -0.004262 -0.021029  -0.010317
9  -0.001173 -0.005416  -0.003789
10 -0.012425 -0.004012  -0.006339
11 -0.027743 -0.005411  -0.027594
12 -0.027591 -0.030341  -0.028180
13 -0.018098 -0.017494  -0.030004
14 -0.007061 -0.007951  -0.013097
15  0.002911  0.002505  -0.002103
16 -0.018964 -0.027315  -0.025915
17 -0.005203 -0.009641  -0.002861
18 -0.013577 -0.031117  -0.027134
19 -0.011646 -0.001475  -0.002706
20 -0.013678 -0.019525  -0.022020
21 -0.012683 -0.017605  -0.008392
22 -0.003694 -0.005125  -0.006624
23 -0.015765 -0.022191  -0.032155
24 -0.016048 -0.038214  -0.037001
25 -0.002362 -0.005727  -0.002042
26 -0.000057 -0.001699  -0.008137
27 -0.022253 -0.033697  -0.036379
28 -0.003825 -0.005891  -0.005994
29 -0.015083 -0.019085  -0.030132

In [3]:
# Class activations from fc layer at same steps
df = pd.read_parquet('fc.parquet')
df.head(10)

    iter_128   iter_512  iter_1024
0 -16.128880 -33.905533 -35.774471
1 -17.411303 -18.838095 -19.650520
2 -24.779648 -23.371977 -34.054203
3 -17.617889 -27.164869 -26.724489
4 -43.198700 -49.920521 -46.642941
5 -13.940953 -25.739523 -17.165216
6 -21.268465 -16.779146 -14.469959
7 -18.418774 -32.793232 -34.763634
8 -13.832937 -27.886215 -19.049696
9 -13.228455 -21.108334 -19.785141